[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_provider = "scm"
update_changelog_on_bump = true
major_version_zero = true
version_files = ["package.json", "frontend/package.json", "backend/pyproject.toml"]
