"""The API reference must describe the application that exists.

The pages under ``frontend/src/content/docs/*/docs/api-reference.md`` are generated by
``storico.scripts.render_api_reference`` and committed, because generated content that is not
reviewed is just a rumour with better formatting. These tests are what makes committing them
safe: they compare the committed bytes against a fresh render, so the docs cannot go on
describing an API that changed underneath them.
"""

from __future__ import annotations

from storico.api.app import create_app
from storico.scripts.render_api_reference import REPO_ROOT, fields_of, render_page, render_pages

METHODS = ("get", "post", "put", "patch", "delete")


def test_committed_pages_match_a_fresh_render():
    pages = render_pages()
    assert pages, "the generator produced no pages at all"
    for path, content in pages.items():
        assert path.exists(), f"{path.relative_to(REPO_ROOT)} is missing; run the generator"
        assert path.read_text(encoding="utf-8") == content, (
            f"{path.relative_to(REPO_ROOT)} is stale: the API changed and the page did not. "
            "Run: conda run -n storico python -m storico.scripts.render_api_reference"
        )


def test_the_render_is_deterministic():
    """The drift guard compares bytes, so a render whose order could vary would make it flaky."""
    spec = create_app().openapi()
    assert render_page(spec, "en") == render_page(spec, "en")


def test_every_operation_in_the_spec_reaches_the_page():
    """A silent drop is the failure mode of a generator: nothing errors, an endpoint vanishes."""
    spec = create_app().openapi()
    page = render_page(spec, "en")
    missing = [
        f"{method.upper()} {path}"
        for path, item in spec["paths"].items()
        for method in METHODS
        if method in item and f"`{method.upper()}` `{path}`" not in page
    ]
    assert missing == []


def test_no_component_reference_leaks_into_the_page():
    """A `$ref` in the rendered prose means the reader is shown a pointer instead of a name."""
    page = render_page(create_app().openapi(), "en")
    assert "#/components" not in page


def test_a_recursive_schema_terminates():
    """The application's spec has no cycle — measured: zero self-references and zero cycles among
    the 60 components — so the guard is exercised here rather than by the output.

    ``seen`` is the whole bound, and this is the shape it exists for: without it, following the
    `parent` reference would call back into `Node` forever.
    """
    spec = {
        "components": {
            "schemas": {
                "Node": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "parent": {"$ref": "#/components/schemas/Node"},
                    },
                    "required": ["name"],
                }
            }
        }
    }
    ref = {"$ref": "#/components/schemas/Node"}
    assert fields_of(ref, spec) == [("name", "string", True), ("parent", "Node", False)]
    # Called again, not mutated: the guard threads a new frozenset instead of adding to a shared one.
    assert fields_of(ref, spec) == fields_of(ref, spec)
