"""Run the whole Alembic chain against a real Postgres and compare the result to the models.

The unit suite builds its schema from the **models** (``Base.metadata.create_all`` in
``tests/conftest.py``), so no test there can notice a migration that fails to add a column a model
declares. The other integration test builds its schema the same way and hand-creates the Postgres
enum types with a shim that exists *solely to paper over the models/migrations gap*. Nothing in the
suite ever executes the migration chain, which means the chain that production runs is unproven.

This module executes it against a Postgres 16 container and asserts two things:

1. ``alembic upgrade head`` runs the chain from an **empty** database and the database ends at the
   head the packaged scripts declare. That is what proves no revision in the chain is broken and
   that the enum types, the ``USING ...::jsonb`` cast and the NOT NULL narrowing actually work on
   Postgres. SQLite cannot run this: the chain depends on all three.
2. Autogenerate's differences between the migrated schema and the models are **exactly** the six
   known, measured differences recorded in this module — no more and no fewer. That is a ratchet,
   not a tolerance: a difference the run reports and the record does not hold fails the test, and
   so does a record entry the run no longer reports, because a stale line turns the record into a
   lie. The six predate this test and are deliberately not fixed here — three of them need a
   decision about which side is authoritative. See ``odd/tasks/schema-drift-gate.md``, section
   "WU3 — the chain measured".

The two container tests are marked ``@pytest.mark.integration`` individually and disabled unless the
Docker daemon is reachable, so they skip on a laptop without a daemon and run for real on GitHub
runners, which do have one. The markers sit on those two tests rather than on the module so that the
URL-shape test below — which needs no Docker — still runs on a machine without a daemon.

To run manually (docker daemon up):

    pytest tests/test_integration/test_migration_chain.py -m integration
"""

from __future__ import annotations

import asyncio
import os
from collections.abc import AsyncGenerator, Iterator
from pathlib import Path
from typing import Any

import pytest
import pytest_asyncio
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import select
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine
from sqlalchemy.pool import NullPool

import storico.infrastructure.database as _database_package
from storico.config.settings import _reset_settings_cache


def _docker_reachable() -> bool:
    """Best-effort check — is the docker daemon pickable in $DOCKER_HOST?

    Same probe as ``tests/test_integration/test_projects_integration.py``, copied rather than
    shared: the marks below evaluate it at import time, and this test file's edit surface has no
    home for a shared helper module. The two copies must move together, or their skip semantics
    silently diverge.
    """
    host = os.environ.get("DOCKER_HOST", "")
    # Docker Desktop default unix socket path:
    socket_path = host.removeprefix("unix://") if host.startswith("unix://") else ""
    if not socket_path:
        socket_path = os.path.expanduser("~/.docker/run/docker.sock")
        if not os.path.exists(socket_path):
            socket_path = "/var/run/docker.sock"
    return os.path.exists(socket_path) and os.access(socket_path, os.W_OK)


# Applied to the two container tests individually, never to the module: the URL-shape test below is
# pure and must run on a machine with no Docker daemon at all.
_needs_docker = pytest.mark.skipif(
    not _docker_reachable(),
    reason="Docker daemon unreachable — this integration test needs docker to spawn a Postgres container via testcontainers.",
)

# The migration scripts sit beside the package they migrate. Resolved from the installed package
# rather than from the working directory (CI runs pytest from ``backend/``, and this repository is
# also exercised from its root) and rather than from ``alembic.ini``, which the production image
# does not contain. This is the same directory ``schema_status`` reads for the expected head.
_ALEMBIC_SCRIPT_LOCATION = Path(_database_package.__file__).resolve().parent / "alembic"

# Alembic owns this table and creates it when the first revision runs. Declared rather than written
# as a SQL string: a table declaration cannot smuggle a caller's input into a statement the way a
# composed string can.
_ALEMBIC_VERSION = sa.Table(
    "alembic_version",
    sa.MetaData(),
    sa.Column("version_num", sa.String(32), nullable=False),
)

# The differences between the migrated schema and the models that have been **measured** and are
# known to exist today. This is a debt list, not a tolerance: the drift test below asserts exact
# equality against it in both directions, so a new difference fails and a resolved one fails too,
# because its line here has gone stale.
#
# Each entry is "<op>:<target>", the normalised shape ``_diff_signature`` produces. All six are
# pre-existing and predate the migration-chain test entirely, and none is fixed here: three of them
# need a decision about which side is authoritative, and one of those may be a missing revision
# rather than a wrong model. The reasoning for every line, and the full table this literal mirrors,
# is in ``odd/tasks/schema-drift-gate.md`` under "WU3 — the chain measured".
_KNOWN_DRIFT: frozenset[str] = frozenset(
    {
        # 0018 creates the `extraction_status_new` enum and no revision ever converts the column to
        # it, so the model declares a type the migrations never produce. Neither side is proven:
        # either the conversion revision is missing, or the enum type was never wanted.
        "modify_type:extractions.status",
        # 0005 creates this column as JSONB and the model under-declares it as JSON. The migrations
        # are authoritative, so the model is the side to change.
        "modify_type:user_preferences.preferences",
        # 0009 converts this column to JSONB explicitly and the model again under-declares it as
        # JSON. The migrations are authoritative, same shape as the line above.
        "modify_type:workspace_prompts.few_shot_examples",
        # 0016 creates this index on purpose and the models do not declare it. The models are the
        # side to change, because a deliberately created index is missing from the metadata.
        "remove_index:idx_tasks_status",
        # Same shape as the line above, on `user_stories.status`. The models are the side to change.
        "remove_index:idx_user_stories_status",
        # 0016 created this index while 0001 had already created `ix_tasks_user_story_id` for the
        # same column, so one column carries two indexes under two names. The migrations are the
        # side to change: one of the two duplicates should go.
        "remove_index:idx_tasks_user_story_id",
    }
)


def _alembic_config(url: str) -> Config:
    """An Alembic config pointing at the packaged scripts and at ``url``.

    The URL travels through ``config.attributes``, the channel ``env.py`` reads. It cannot travel
    through the ``sqlalchemy.url`` option: ``alembic.ini``'s placeholder for that option is truthy,
    so an ``env.py`` emptiness check could never see a caller's override (see ``env.py``). A
    ``Config`` built here needs no ini file at all, which is also why it works from any directory.
    """
    config = Config()
    config.set_main_option("script_location", str(_ALEMBIC_SCRIPT_LOCATION))
    config.attributes["sqlalchemy_url"] = url
    return config


def _alembic_ready_url(container_url: str) -> str:
    """The container's URL in, the URL string Alembic receives out.

    The container keeps its own *sync* driver, which is what its readiness probe wants; only the URL
    handed to Alembic moves to asyncpg. ``env.py`` uses a supplied URL verbatim, so what is returned
    must already be asyncpg-acceptable.

    ``render_as_string(hide_password=False)`` is load-bearing, not a style choice: ``URL.__str__``
    **masks the password as ``***``**, so ``str(make_url(...).set(drivername=...))`` hands the
    container the literal password ``***`` and it answers ``InvalidPasswordError`` while the call
    site looks perfectly correct. This code path has no way around it by passing the ``URL`` object
    the way the other integration test does — ``env.py`` puts this value into a ``configparser``
    option, which requires a string.
    """
    return (
        make_url(container_url)
        .set(drivername="postgresql+asyncpg")
        .render_as_string(hide_password=False)
    )


def test_the_alembic_url_carries_the_real_password() -> None:
    """The string handed to Alembic keeps the password the container was created with.

    No Docker, no database, no event loop: this is a pure string transformation, and it exists so the
    masking trap cannot come back unnoticed. It fails the moment ``_alembic_ready_url`` renders the
    URL through ``URL.__str__`` again — the edit that caused the original failure.
    """
    alembic_url = _alembic_ready_url("postgresql+psycopg2://test:test@localhost:32769/test")

    assert "***" not in alembic_url, (
        "URL.__str__ masks the password as '***'; Alembic would then authenticate with that "
        f"literal string and the container would reject it: {alembic_url}"
    )
    assert alembic_url == "postgresql+asyncpg://test:test@localhost:32769/test"


@pytest.fixture(scope="module")
def pg_url() -> Iterator[str]:
    """Start Postgres 16 in a testcontainer and yield an Alembic-ready asyncpg URL for it.

    The URL is rendered by ``_alembic_ready_url``, which keeps the password SQLAlchemy would
    otherwise mask; that function's own test pins the behaviour without needing the daemon.
    """
    # Import lazily so the module import itself never blocks on testcontainers — testcontainers
    # imports docker, which is heavy and may pull images.
    from testcontainers.community.postgres import PostgresContainer

    with PostgresContainer("postgres:16-alpine") as pg:
        yield _alembic_ready_url(pg.get_connection_url())


@pytest.fixture(scope="module")
def alembic_config(pg_url: str) -> Config:
    """The config both tests use — one container, one URL, one script location."""
    return _alembic_config(pg_url)


@pytest.fixture(scope="module")
def throwaway_encryption_key() -> Iterator[None]:
    """Put a throwaway master key in the environment so the chain can reach head.

    Revision ``0024`` encrypts the credentials already stored in
    ``workspace_llm_configs.api_key``, and it refuses to run at all when the master key is absent:
    a migration that reports success while leaving credentials in plaintext is the exact failure
    that revision exists to remove. The refusal is correct behaviour, and it makes the master key
    an operational requirement of **any** upgrade to head — a fresh database or a restore just as
    much as production, where the container carries the key in its own ``.env`` (a file outside
    version control, so a deployment that omits it fails here rather than in silence).

    This is why the key is supplied rather than asserted away: the container database is empty, so
    nothing is encrypted and the key's value is irrelevant. It is generated per run instead of
    hardcoded so this module can never be read as saying a real key belongs in the repository.

    Ordering is load-bearing, and the reason is the settings cache: ``Settings.load()`` delegates to
    ``get_settings``, which is wrapped in ``lru_cache(maxsize=1)`` and is therefore process-wide and
    possibly already primed during collection, before this fixture ran. The cache is cleared after
    the environment changes; without that, ``0024`` would read a ``Settings`` built before the key
    existed, and the failure would look like the migration's own guard instead of this fixture's
    ordering.

    ``pytest.MonkeyPatch()`` is constructed by hand because the ``monkeypatch`` fixture is
    function-scoped and cannot be injected into a module-scoped fixture. Both the patch and the
    cache are undone on teardown, so neither the environment variable nor a ``Settings`` built from
    this key outlives the module.
    """
    # Imported lazily, like testcontainers above, so importing this module stays cheap.
    from cryptography.fernet import Fernet

    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setenv("STORICO_ENCRYPTION_KEY", Fernet.generate_key().decode())
    # Drop any instance built before the key existed, or 0024 never sees it.
    _reset_settings_cache()
    try:
        yield
    finally:
        monkeypatch.undo()
        # Restore the cache too: the instance built for the chain above holds the throwaway key.
        _reset_settings_cache()


@pytest_asyncio.fixture(scope="module", loop_scope="module")
async def migrated_engine(
    pg_url: str,
    alembic_config: Config,
    throwaway_encryption_key: None,
) -> AsyncGenerator[AsyncEngine, None]:
    """Run the whole chain once against the empty container database, then yield an engine on it.

    ``command.upgrade`` is invoked through ``asyncio.to_thread`` because ``env.py`` ends in
    ``asyncio.run(run_async_migrations())``: calling Alembic from inside this fixture's running
    event loop raises ``asyncio.run() cannot be called from a running event loop``.

    ``throwaway_encryption_key`` is a dependency rather than an unused parameter: it must be set up
    before the upgrade runs, and naming it here is what orders the two.
    """
    await asyncio.to_thread(command.upgrade, alembic_config, "head")

    engine = create_async_engine(pg_url, poolclass=NullPool)
    yield engine
    await engine.dispose()


@pytest.mark.integration
@_needs_docker
@pytest.mark.asyncio(loop_scope="module")
async def test_the_chain_from_scratch_reaches_the_head_the_scripts_declare(
    alembic_config: Config,
    migrated_engine: AsyncEngine,
) -> None:
    """An empty database upgraded to head records the head the packaged scripts declare.

    A revision that cannot run on Postgres — a missing enum type, a ``USING`` cast that does not
    type-check, a NOT NULL narrowing over existing rows — fails the upgrade in the fixture before
    this test runs at all. What is left to prove is that the chain finishes where it claims to.
    """
    declared_head = ScriptDirectory.from_config(alembic_config).get_current_head()
    assert declared_head is not None, "the packaged scripts declare no head at all"

    async with migrated_engine.connect() as conn:
        recorded = (await conn.execute(select(_ALEMBIC_VERSION.c.version_num))).scalar_one()

    assert recorded == declared_head, (
        f"the chain stopped at {recorded} while the scripts declare head {declared_head}"
    )


#: Ops whose diff tuple is ``(name, schema, table, column, ...)``. The trailing members carry
#: types, defaults and comments, which ``_diff_signature`` leaves out on purpose.
_COLUMN_LEVEL_OPS = frozenset(
    {
        "add_column",
        "remove_column",
        "modify_type",
        "modify_nullable",
        "modify_default",
        "modify_comment",
    }
)

#: Ops whose diff tuple is ``(name, object)`` and whose target is that object's own ``name``:
#: indexes, tables, constraints and table comments.
_NAMED_OBJECT_OPS = frozenset(
    {
        "add_index",
        "remove_index",
        "add_table",
        "remove_table",
        "add_constraint",
        "remove_constraint",
        "add_fk",
        "remove_fk",
        "add_table_comment",
        "remove_table_comment",
    }
)


def _diff_tuples(diffs: list[Any]) -> Iterator[tuple[Any, ...]]:
    """One diff tuple per difference, unwrapping the one op that reports several at once.

    Every leaf op's ``to_diff_tuple`` returns a single ``(op_name, ...)`` tuple, except
    ``AlterColumnOp``: that one returns a *list* of them, one per column attribute it would
    modify. ``command.check`` flattens the op tree but not that inner list, so an entry in
    ``diffs`` is either the tuple itself or a list of tuples. A diff tuple always starts with the
    op name as a string, which is what tells the two apart.
    """
    for diff in diffs:
        if isinstance(diff[0], str):
            yield diff
        else:
            yield from diff


def _diff_signature(diff: tuple[Any, ...]) -> str:
    """Reduce one autogenerate difference to a stable ``"<op>:<target>"`` signature.

    Built from the op name and the target's own *name*, never from the diff's ``repr``: the tuples
    embed live ``Index``, ``Table`` and type objects whose reprs carry memory addresses, so a
    repr-based assertion would be non-deterministic across runs and fragile across a SQLAlchemy
    release. Type details are left out for the same reason — the signature names the *difference*,
    it does not render it, so it survives a version bump that changes how types print. An op shape
    this test has not seen before still yields a signature of its own, so it fails the ratchet as
    the new difference it is instead of being dropped.
    """
    op = diff[0]
    if op in _COLUMN_LEVEL_OPS:
        # The column member is a plain name for the "modify_*" ops and a Column object for
        # add/remove, hence the getattr.
        return f"{op}:{diff[2]}.{getattr(diff[3], 'name', diff[3])}"
    if op in _NAMED_OBJECT_OPS:
        return f"{op}:{diff[1].name}"
    # Unknown shape: its name plus its own scalar members, and nothing else. No `_KNOWN_DRIFT`
    # entry can match this, so an unrecognised op is a loud failure rather than a silent drop.
    scalars = "|".join(str(part) for part in diff[1:] if isinstance(part, str | int))
    return f"{op}:{scalars}" if scalars else op


@pytest.mark.integration
@_needs_docker
@pytest.mark.asyncio(loop_scope="module")
async def test_the_migrated_schema_drift_equals_the_recorded_gap(
    alembic_config: Config,
    migrated_engine: AsyncEngine,
) -> None:
    """The autogenerate diff equals ``_KNOWN_DRIFT`` exactly — a ratchet, not a tolerance.

    Six differences between the migrated schema and the models were measured on CI, because the
    chain needs a real Postgres and there is no Docker daemon on the author's machine; they are
    recorded in ``_KNOWN_DRIFT`` and in ``odd/tasks/schema-drift-gate.md`` under "WU3 — the chain
    measured". Reconciling them is deliberately not this test's job: three of the six need a
    decision about which side is authoritative.

    The assertion is an exact set match in **both** directions, and that is what makes this a
    ratchet rather than a tolerance:

    * a difference the run reports that is not recorded is a **new** divergence, and it fails.
      That is the failure mode this whole gate exists to catch: a schema change arriving without
      anyone noticing.
    * a recorded entry the run no longer reports is a **resolved** difference whose allowlist
      line has gone stale, and it fails too. Without this half, the record rots into a lie the
      first time somebody reconciles one of the six.

    Both sets are printed on failure, so the reader can tell which case they are in. Fixing the
    schema or the model to make one difference vanish must be a separate change that deletes its
    line here as part of the same work unit.
    """
    try:
        await asyncio.to_thread(command.check, alembic_config)
    except AutogenerateDiffsDetected as exc:
        found = {_diff_signature(diff) for diff in _diff_tuples(exc.diffs)}
    else:
        # No differences at all: every recorded entry is now stale, and the comparison says so.
        found = set()

    new_differences = sorted(found - _KNOWN_DRIFT)
    stale_entries = sorted(_KNOWN_DRIFT - found)

    assert not new_differences and not stale_entries, (
        "the migrated schema and the models disagree in a way the recorded drift does not cover. "
        f"The record holds {len(_KNOWN_DRIFT)} known differences; this run reported {len(found)}.\n"
        f"  new differences (reported by the run, absent from the record): {new_differences or 'none'}\n"
        f"  stale entries (recorded, no longer reported): {stale_entries or 'none'}\n"
        "A new difference is drift that arrived unnoticed and must be understood before it is "
        "recorded. A stale entry means its difference is gone and the record must lose that line. "
        "See odd/tasks/schema-drift-gate.md, 'WU3 — the chain measured', for what each one is and "
        "which side looks authoritative."
    )
