"""Run the whole Alembic chain against a real Postgres and compare the result to the models.

The unit suite builds its schema from the **models** (``Base.metadata.create_all`` in
``tests/conftest.py``), so no test there can notice a migration that fails to add a column a model
declares. The other integration test builds its schema the same way and hand-creates the Postgres
enum types with a shim that exists *solely to paper over the models/migrations gap*. Nothing in the
suite ever executes the migration chain, which means the chain that production runs is unproven.

This module executes it against a Postgres 16 container and asserts two things:

1. ``alembic upgrade head`` runs the chain from an **empty** database and the database ends at the
   head the packaged scripts declare. That is what proves no revision in the chain is broken and
   that the enum types, the ``USING ...::jsonb`` cast and the NOT NULL narrowing actually work on
   Postgres. SQLite cannot run this: the chain depends on all three.
2. Autogenerate reports no differences between the migrated schema and the models — ``alembic
   check`` semantics. A difference is drift between the two and is reported as a failure, not
   accommodated here.

This test is marked ``@pytest.mark.integration`` and disabled unless the Docker daemon is reachable,
so it skips on a laptop without a daemon and runs for real on GitHub runners, which do have one.

To run manually (docker daemon up):

    pytest tests/test_integration/test_migration_chain.py -m integration
"""

from __future__ import annotations

import asyncio
import os
from collections.abc import AsyncGenerator, Iterator
from pathlib import Path

import pytest
import pytest_asyncio
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import select
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine
from sqlalchemy.pool import NullPool

import storico.infrastructure.database as _database_package


def _docker_reachable() -> bool:
    """Best-effort check — is the docker daemon pickable in $DOCKER_HOST?

    Same probe as ``tests/test_integration/test_projects_integration.py``, copied rather than
    shared: ``pytestmark`` below evaluates it at import time, and this test file's edit surface has
    no home for a shared helper module. The two copies must move together, or their skip semantics
    silently diverge.
    """
    host = os.environ.get("DOCKER_HOST", "")
    # Docker Desktop default unix socket path:
    socket_path = host.removeprefix("unix://") if host.startswith("unix://") else ""
    if not socket_path:
        socket_path = os.path.expanduser("~/.docker/run/docker.sock")
        if not os.path.exists(socket_path):
            socket_path = "/var/run/docker.sock"
    return os.path.exists(socket_path) and os.access(socket_path, os.W_OK)


pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        not _docker_reachable(),
        reason="Docker daemon unreachable — this integration test needs docker to spawn a Postgres container via testcontainers.",
    ),
]

# The migration scripts sit beside the package they migrate. Resolved from the installed package
# rather than from the working directory (CI runs pytest from ``backend/``, and this repository is
# also exercised from its root) and rather than from ``alembic.ini``, which the production image
# does not contain. This is the same directory ``schema_status`` reads for the expected head.
_ALEMBIC_SCRIPT_LOCATION = Path(_database_package.__file__).resolve().parent / "alembic"

# Alembic owns this table and creates it when the first revision runs. Declared rather than written
# as a SQL string: a table declaration cannot smuggle a caller's input into a statement the way a
# composed string can.
_ALEMBIC_VERSION = sa.Table(
    "alembic_version",
    sa.MetaData(),
    sa.Column("version_num", sa.String(32), nullable=False),
)


def _alembic_config(url: str) -> Config:
    """An Alembic config pointing at the packaged scripts and at ``url``.

    The URL travels through ``config.attributes``, the channel ``env.py`` reads. It cannot travel
    through the ``sqlalchemy.url`` option: ``alembic.ini``'s placeholder for that option is truthy,
    so an ``env.py`` emptiness check could never see a caller's override (see ``env.py``). A
    ``Config`` built here needs no ini file at all, which is also why it works from any directory.
    """
    config = Config()
    config.set_main_option("script_location", str(_ALEMBIC_SCRIPT_LOCATION))
    config.attributes["sqlalchemy_url"] = url
    return config


@pytest.fixture(scope="module")
def pg_url() -> Iterator[str]:
    """Start Postgres 16 in a testcontainer and yield an asyncpg URL for it.

    The container keeps its own *sync* driver, which is what its readiness probe wants; only the URL
    handed to Alembic moves to asyncpg. ``env.py`` uses a supplied URL verbatim, so what is passed
    here must already be asyncpg-acceptable.
    """
    # Import lazily so the module import itself never blocks on testcontainers — testcontainers
    # imports docker, which is heavy and may pull images.
    from testcontainers.community.postgres import PostgresContainer

    with PostgresContainer("postgres:16-alpine") as pg:
        yield str(make_url(pg.get_connection_url()).set(drivername="postgresql+asyncpg"))


@pytest.fixture(scope="module")
def alembic_config(pg_url: str) -> Config:
    """The config both tests use — one container, one URL, one script location."""
    return _alembic_config(pg_url)


@pytest_asyncio.fixture(scope="module", loop_scope="module")
async def migrated_engine(pg_url: str, alembic_config: Config) -> AsyncGenerator[AsyncEngine, None]:
    """Run the whole chain once against the empty container database, then yield an engine on it.

    ``command.upgrade`` is invoked through ``asyncio.to_thread`` because ``env.py`` ends in
    ``asyncio.run(run_async_migrations())``: calling Alembic from inside this fixture's running
    event loop raises ``asyncio.run() cannot be called from a running event loop``.
    """
    await asyncio.to_thread(command.upgrade, alembic_config, "head")

    engine = create_async_engine(pg_url, poolclass=NullPool)
    yield engine
    await engine.dispose()


@pytest.mark.asyncio(loop_scope="module")
async def test_the_chain_from_scratch_reaches_the_head_the_scripts_declare(
    alembic_config: Config,
    migrated_engine: AsyncEngine,
) -> None:
    """An empty database upgraded to head records the head the packaged scripts declare.

    A revision that cannot run on Postgres — a missing enum type, a ``USING`` cast that does not
    type-check, a NOT NULL narrowing over existing rows — fails the upgrade in the fixture before
    this test runs at all. What is left to prove is that the chain finishes where it claims to.
    """
    declared_head = ScriptDirectory.from_config(alembic_config).get_current_head()
    assert declared_head is not None, "the packaged scripts declare no head at all"

    async with migrated_engine.connect() as conn:
        recorded = (await conn.execute(select(_ALEMBIC_VERSION.c.version_num))).scalar_one()

    assert recorded == declared_head, (
        f"the chain stopped at {recorded} while the scripts declare head {declared_head}"
    )


@pytest.mark.asyncio(loop_scope="module")
async def test_the_migrated_schema_matches_the_models(
    alembic_config: Config,
    migrated_engine: AsyncEngine,
) -> None:
    """Autogenerate must find nothing to do: the migrated schema equals the models' metadata.

    This is ``alembic check``, and its assertion is deliberately strict: a difference reported on
    the first CI run is the measurement the drift gate needs, not a reason to soften this test. (A
    ``None`` or empty ``target_metadata`` cannot make it pass vacuously — Alembic raises
    ``CommandError`` for autogenerate without metadata, and an empty metadata reports every migrated
    table as to-be-dropped.)
    """
    try:
        await asyncio.to_thread(command.check, alembic_config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"the migrated schema and the models differ: {exc.diffs}")
