"use client"

import type { LucideIcon } from "lucide-react"
import {
  Backpack,
  Blocks,
  BrickWall,
  Briefcase,
  Bug,
  Building2,
  Cable,
  Cake,
  ChartBarBig,
  ChartLine,
  ChartPie,
  Cloud,
  Code,
  Codepen,
  Coffee,
  Command,
  Compass,
  Cone,
  Construction,
  Container,
  Cookie,
  Cpu,
  Crown,
  Database,
  Dna,
  DraftingCompass,
  Droplets,
  Feather,
  Figma,
  Flag,
  FlaskConical,
  FlaskRound,
  FolderGit2,
  FolderKanban,
  Forklift,
  Frame,
  Gamepad2,
  GanttChart,
  Gem,
  GitBranch,
  GitMerge,
  Github,
  Globe,
  Hammer,
  HardDrive,
  Hash,
  Headphones,
  HeartPulse,
  Hexagon,
  House,
  Image,
  Inbox,
  Infinity,
  Key,
  KeyRound,
  Languages,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link,
  ListTodo,
  Lock,
  Map,
  Medal,
  Megaphone,
  MessageSquareText,
  Microchip,
  Milestone,
  Monitor,
  Mountain,
  Mouse,
  Music,
  Network,
  NotebookPen,
  NotebookText,
  Nut,
  Palette,
  PanelTop,
  Paperclip,
  PencilRuler,
  Phone,
  Pi,
  PiggyBank,
  Pizza,
  Plug,
  PlugZap,
  Pocket,
  Podcast,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  RadioReceiver,
  Rocket,
  Ruler,
  Scale,
  Scissors,
  ScreenShare,
  Server,
  Settings,
  Share2,
  Shield,
  Ship,
  Shirt,
  ShoppingCart,
  Shovel,
  Shrub,
  Sigma,
  Siren,
  SlidersVertical,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  Sparkles,
  Speaker,
  Spline,
  Sprout,
  SquareKanban,
  SquareTerminal,
  Star,
  Stethoscope,
  Sticker,
  Store,
  Sun,
  SwatchBook,
  Sword,
  Table2,
  Tablet,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTubes,
  TextSearch,
  Ticket,
  Timer,
  ToyBrick,
  TrainTrack,
  Trash2,
  TreeDeciduous,
  Trello,
  Trophy,
  Truck,
  Wrench,
  Zap,
} from "lucide-react"

/* ── static icon map for display (sidebar, cards, etc.) ──
 *
 * DynamicIcon is NOT used here because:
 *   - Static imports avoid extra network requests per icon
 *   - No SSR flash — icons render immediately
 *   - Bundle-impact is bounded by what we actually map
 *
 * If an icon name isn't in this map, the fallback is used.
 * New icons added to the picker's POPULAR_ICONS should be
 * added here as needed.
 */
const ICONS: Record<string, LucideIcon> = {
  "backpack": Backpack,
  "blocks": Blocks,
  "brick-wall": BrickWall,
  "briefcase": Briefcase,
  "bug": Bug,
  "building-2": Building2,
  "cable": Cable,
  "cake": Cake,
  "chart-bar-big": ChartBarBig,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "cloud": Cloud,
  "code": Code,
  "codepen": Codepen,
  "coffee": Coffee,
  "command": Command,
  "compass": Compass,
  "cone": Cone,
  "construction": Construction,
  "container": Container,
  "cookie": Cookie,
  "cpu": Cpu,
  "crown": Crown,
  "database": Database,
  "dna": Dna,
  "drafting-compass": DraftingCompass,
  "droplets": Droplets,
  "feather": Feather,
  "figma": Figma,
  "flag": Flag,
  "flask-conical": FlaskConical,
  "flask-round": FlaskRound,
  "folder-git-2": FolderGit2,
  "folder-kanban": FolderKanban,
  "forklift": Forklift,
  "frame": Frame,
  "gamepad-2": Gamepad2,
  "gantt-chart": GanttChart,
  "gem": Gem,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  "github": Github,
  "globe": Globe,
  "hammer": Hammer,
  "hard-drive": HardDrive,
  "hash": Hash,
  "headphones": Headphones,
  "heart-pulse": HeartPulse,
  "hexagon": Hexagon,
  "house": House,
  "image": Image,
  "inbox": Inbox,
  "infinity": Infinity,
  "key": Key,
  "key-round": KeyRound,
  "languages": Languages,
  "layers": Layers,
  "layout-dashboard": LayoutDashboard,
  "lightbulb": Lightbulb,
  "link": Link,
  "list-todo": ListTodo,
  "lock": Lock,
  "map": Map,
  "medal": Medal,
  "megaphone": Megaphone,
  "message-square-text": MessageSquareText,
  "microchip": Microchip,
  "milestone": Milestone,
  "monitor": Monitor,
  "mountain": Mountain,
  "mouse": Mouse,
  "music": Music,
  "network": Network,
  "notebook-pen": NotebookPen,
  "notebook-text": NotebookText,
  "nut": Nut,
  "palette": Palette,
  "panel-top": PanelTop,
  "paperclip": Paperclip,
  "pencil-ruler": PencilRuler,
  "phone": Phone,
  "pi": Pi,
  "piggy-bank": PiggyBank,
  "pizza": Pizza,
  "plug": Plug,
  "plug-zap": PlugZap,
  "pocket": Pocket,
  "podcast": Podcast,
  "power": Power,
  "printer": Printer,
  "puzzle": Puzzle,
  "qr-code": QrCode,
  "radio": Radio,
  "radio-receiver": RadioReceiver,
  "rocket": Rocket,
  "ruler": Ruler,
  "scale": Scale,
  "scissors": Scissors,
  "screen-share": ScreenShare,
  "server": Server,
  "settings": Settings,
  "share-2": Share2,
  "shield": Shield,
  "ship": Ship,
  "shirt": Shirt,
  "shopping-cart": ShoppingCart,
  "shovel": Shovel,
  "shrub": Shrub,
  "sigma": Sigma,
  "siren": Siren,
  "sliders-vertical": SlidersVertical,
  "smartphone": Smartphone,
  "smile": Smile,
  "snail": Snail,
  "snowflake": Snowflake,
  "sparkles": Sparkles,
  "speaker": Speaker,
  "spline": Spline,
  "sprout": Sprout,
  "square-kanban": SquareKanban,
  "square-terminal": SquareTerminal,
  "star": Star,
  "stethoscope": Stethoscope,
  "sticker": Sticker,
  "store": Store,
  "sun": Sun,
  "swatch-book": SwatchBook,
  "sword": Sword,
  "table-2": Table2,
  "tablet": Tablet,
  "tag": Tag,
  "tags": Tags,
  "target": Target,
  "telescope": Telescope,
  "tent": Tent,
  "terminal": Terminal,
  "test-tubes": TestTubes,
  "text-search": TextSearch,
  "ticket": Ticket,
  "timer": Timer,
  "toy-brick": ToyBrick,
  "train-track": TrainTrack,
  "trash-2": Trash2,
  "tree-deciduous": TreeDeciduous,
  "trello": Trello,
  "trophy": Trophy,
  "truck": Truck,
  "wrench": Wrench,
  "zap": Zap,
}

export interface IconDisplayProps {
  name?: string | null
  className?: string
  /** Fallback icon component when name is missing or unknown */
  fallback?: LucideIcon
}

/**
 * Renders a static Lucide icon by name.
 *
 * - Uses statically imported icons (no dynamic chunks, no SSR flash)
 * - Falls back to `FolderKanban` (or custom fallback) when the name
 *   is null, undefined, or not in the map
 * - New icons added to `POPULAR_ICONS` in the picker should be
 *   added to the ICONS map here for display support
 */
export function IconDisplay({ name, className, fallback: Fallback = FolderKanban }: IconDisplayProps) {
  if (!name) return <Fallback className={className} />

  const Icon = ICONS[name] ?? Fallback
  return <Icon className={className} />
}
