"""add avatar_url to users

Revision ID: 3fefad99b84d
Revises: 0002
Create Date: 2026-07-09 11:56:53.144350
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fefad99b84d'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_owner_id_users'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_owner_id_users'), 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(op.f('fk_projects_owner_id_users'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_owner_id_users'), 'projects', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
